<?php

declare(strict_types=1);

namespace Mautic\CoreBundle\Tests\Unit\Form\Type;

use Mautic\CoreBundle\Form\Type\SortableValueLabelListType;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

final class SortableValueLabelListTypeTest extends TestCase
{
    public function testBuildFormMakesValueOptional(): void
    {
        $builder = $this->createMock(FormBuilderInterface::class);
        $type    = new SortableValueLabelListType();

        $call = 0;
        $builder->expects($this->exactly(2))
            ->method('add')
            ->with($this->callback(function (string $name): bool {
                $expected = [
                    ['label', 'value'],
                ];

                return in_array($name, $expected[0], true);
            }),
                TextType::class,
                $this->callback(function (array $options) use (&$call): bool {
                    $expectedOptions = [
                        [
                            'label'          => 'mautic.core.label',
                            'error_bubbling' => true,
                            'attr'           => ['class' => 'form-control'],
                        ],
                        [
                            'label'          => 'mautic.core.value_autogenerated',
                            'error_bubbling' => true,
                            'required'       => false,
                            'attr'           => ['class' => 'form-control'],
                        ],
                    ];
                    $result = $options === $expectedOptions[$call];
                    ++$call;

                    return $result;
                })
            );

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->isCallable());

        $type->buildForm($builder, []);
    }

    public function testBuildViewSetsViewVariables(): void
    {
        $type = new SortableValueLabelListType();
        $form = $this->createStub(FormInterface::class);
        $view = $this->createStub(FormView::class);

        $options = [
            'attr' => [
                'preaddon_attr'  => ['class' => 'test-preaddon'],
                'postaddon_attr' => ['class' => 'test-postaddon'],
                'preaddon'       => 'ri-test',
                'postaddon'      => 'ri-test-end',
            ],
        ];

        $view->vars = [];

        $type->buildView($view, $form, $options);

        $this->assertEquals(['class' => 'test-preaddon'], $view->vars['preaddonAttr']);
        $this->assertEquals(['class' => 'test-postaddon'], $view->vars['postaddonAttr']);
        $this->assertEquals('ri-test', $view->vars['preaddon']);
        $this->assertEquals('ri-test-end', $view->vars['postaddon']);
    }

    public function testBuildViewWithEmptyOptions(): void
    {
        $type = new SortableValueLabelListType();
        $form = $this->createStub(FormInterface::class);
        $view = $this->createStub(FormView::class);

        $options    = ['attr' => []];
        $view->vars = [];

        $type->buildView($view, $form, $options);

        $this->assertEquals([], $view->vars['preaddonAttr']);
        $this->assertEquals([], $view->vars['postaddonAttr']);
        $this->assertEquals([], $view->vars['preaddon']);
        $this->assertEquals([], $view->vars['postaddon']);
    }

    /**
     * @param MockObject&FormBuilderInterface $builder
     */
    private function getEventListenerFromBuildForm(SortableValueLabelListType $type, MockObject $builder): callable
    {
        $eventListener = null;
        // @phpstan-ignore-next-line
        $builder->expects($this->exactly(2))
            ->method('add');
        // @phpstan-ignore-next-line
        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->callback(function ($callback) use (&$eventListener): true {
                $eventListener = $callback;

                return true;
            }));
        $type->buildForm($builder, []);
        $this->assertNotNull($eventListener, 'Event listener should be set');

        return $eventListener;
    }

    #[DataProvider('eventListenerDataProvider')]
    public function testFormEventListenerVariants(mixed $data, bool $shouldSetData, ?string $expectedValue = null): void
    {
        $type          = new SortableValueLabelListType();
        $eventListener = $this->getEventListenerFromBuildForm($type, $this->createMock(FormBuilderInterface::class));

        $event         = $this->createMock(FormEvent::class);
        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);
        if ($shouldSetData) {
            $event->expects($this->once())
                ->method('setData')
                ->willReturnCallback(function (array $newData) use ($data, $expectedValue): void {
                    $this->assertSame($data['label'], $newData['label']);
                    $this->assertSame($expectedValue, $newData['value']);
                });
        } else {
            $event->expects($this->never())
                ->method('setData');
        }
        $eventListener($event);
    }

    /**
     * @return \Iterator<string, array{mixed, bool, (string|null)}>
     */
    public static function eventListenerDataProvider(): \Iterator
    {
        yield 'auto generates value' => [
            ['label' => 'Test Label', 'value' => ''],
            true,
            'test_label',
        ];
        yield 'does not modify when value exists' => [
            ['label' => 'Test Label', 'value' => 'existing_value'],
            false,
            null,
        ];
        yield 'does not modify when label empty' => [
            ['label' => '', 'value' => ''],
            false,
            null,
        ];
        yield 'handles non-array data' => [
            'not_an_array',
            false,
            null,
        ];
    }

    #[DataProvider('slugifyDataProvider')]
    public function testFormEventListenerGeneratesSlug(string $input, string $expected): void
    {
        $type          = new SortableValueLabelListType();
        $eventListener = $this->getEventListenerFromBuildForm($type, $this->createMock(FormBuilderInterface::class));
        $event         = $this->createMock(FormEvent::class);

        $data = ['label' => $input, 'value' => ''];
        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);

        if (!empty($input)) {
            $event->expects($this->once())
                ->method('setData')
                ->willReturnCallback(function (array $newData) use ($data, $expected): void {
                    $this->assertSame($data['label'], $newData['label']);
                    $this->assertSame($expected, $newData['value']);
                });
        } else {
            $event->expects($this->never())
                ->method('setData');
        }

        $eventListener($event);
    }

    /**
     * @return \Iterator<int, array{string, string}>
     */
    public static function slugifyDataProvider(): \Iterator
    {
        yield ['My Option', 'my_option'];
        yield ['First Choice!', 'first_choice'];
        yield ['Test-Value_123', 'testvalue_123'];
        yield ['Special@#$%Characters', 'specialcharacters'];
        yield ['  Trimmed  Spaces  ', 'trimmed_spaces'];
        yield ['Multiple___Underscores', 'multiple_underscores'];
        yield ['Àccénted Chàracters', 'accented_characters'];
        yield ['Привет мир', 'privet_mir'];
        yield ['', ''];
        yield ['123Numbers', '123numbers'];
        yield ['Numéro', 'numero'];
        yield ['Âge', 'age'];
        yield ['Straße', 'strasse'];
        yield ['Über', 'uber'];
        yield ['Teléfono', 'telefono'];
        yield ['Dirección', 'direccion'];
        yield ['Coração', 'coracao'];
        yield ['Ação', 'acao'];
        yield ['Födelsedag', 'fodelsedag'];
        yield ['Äktenskap', 'aktenskap'];
        yield ['Номер', 'nomer'];
        yield ['Адрес', 'adres'];
        yield ['电话', 'dian_hua'];
        yield ['地址', 'de_zhi'];
        yield ['電話番号', 'dian_hua_fan_hao'];
        yield ['住所', 'zhu_suo'];
        yield ['رقم', 'rqm'];
        yield ['عنوان', 'nwan'];
        yield ['Adres', 'adres'];
        yield ['Yaş', 'yas'];
        yield ['Adresa', 'adresa'];
        yield ['Číslo', 'cislo'];
        yield ['Ulica', 'ulica'];
        yield ['Wiek', 'wiek'];
        yield ['Cím', 'cim'];
        yield ['Születésnap', 'szuletesnap'];
        yield ['Διεύθυνση', 'dieuthynse'];
        yield ['Ηλικία', 'elikia'];
        yield ['주소', 'juso'];
        yield ['전화번호', 'jeonhwabeonho'];
    }
}
