<?php

declare(strict_types=1);

namespace Mautic\CoreBundle\Tests\Unit\Form\Type;

use Mautic\CoreBundle\Form\Type\SortableValueLabelListType;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

final class SortableValueLabelListTypeTest extends TestCase
{
    public function testBuildFormMakesValueOptional(): void
    {
        $builder = $this->createMock(FormBuilderInterface::class);
        $type    = new SortableValueLabelListType();

        $call = 0;
        $builder->expects($this->exactly(2))
            ->method('add')
            ->with($this->callback(function ($name) {
                $expected = [
                    ['label', 'value'],
                ];

                return in_array($name, $expected[0], true);
            }),
                $this->callback(function ($type) {
                    return TextType::class === $type;
                }),
                $this->callback(function ($options) use (&$call) {
                    $expectedOptions = [
                        [
                            'label'          => 'mautic.core.label',
                            'error_bubbling' => true,
                            'attr'           => ['class' => 'form-control'],
                        ],
                        [
                            'label'          => 'mautic.core.value_autogenerated',
                            'error_bubbling' => true,
                            'required'       => false,
                            'attr'           => ['class' => 'form-control'],
                        ],
                    ];
                    $result = $options === $expectedOptions[$call];
                    ++$call;

                    return $result;
                })
            );

        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->isType('callable'));

        $type->buildForm($builder, []);
    }

    public function testBuildViewSetsViewVariables(): void
    {
        $type = new SortableValueLabelListType();
        $form = $this->createMock(FormInterface::class);
        $view = $this->createMock(FormView::class);

        $options = [
            'attr' => [
                'preaddon_attr'  => ['class' => 'test-preaddon'],
                'postaddon_attr' => ['class' => 'test-postaddon'],
                'preaddon'       => 'ri-test',
                'postaddon'      => 'ri-test-end',
            ],
        ];

        $view->vars = [];

        $type->buildView($view, $form, $options);

        $this->assertEquals(['class' => 'test-preaddon'], $view->vars['preaddonAttr']);
        $this->assertEquals(['class' => 'test-postaddon'], $view->vars['postaddonAttr']);
        $this->assertEquals('ri-test', $view->vars['preaddon']);
        $this->assertEquals('ri-test-end', $view->vars['postaddon']);
    }

    public function testBuildViewWithEmptyOptions(): void
    {
        $type = new SortableValueLabelListType();
        $form = $this->createMock(FormInterface::class);
        $view = $this->createMock(FormView::class);

        $options    = ['attr' => []];
        $view->vars = [];

        $type->buildView($view, $form, $options);

        $this->assertEquals([], $view->vars['preaddonAttr']);
        $this->assertEquals([], $view->vars['postaddonAttr']);
        $this->assertEquals([], $view->vars['preaddon']);
        $this->assertEquals([], $view->vars['postaddon']);
    }

    private function getEventListenerFromBuildForm(SortableValueLabelListType $type, FormBuilderInterface $builder): callable
    {
        $eventListener = null;
        // @phpstan-ignore-next-line
        $builder->expects($this->exactly(2))
            ->method('add');
        // @phpstan-ignore-next-line
        $builder->expects($this->once())
            ->method('addEventListener')
            ->with(FormEvents::PRE_SUBMIT, $this->callback(function ($callback) use (&$eventListener) {
                $eventListener = $callback;

                return true;
            }));
        $type->buildForm($builder, []);
        $this->assertNotNull($eventListener, 'Event listener should be set');

        return $eventListener;
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('eventListenerDataProvider')]
    public function testFormEventListenerVariants(mixed $data, bool $shouldSetData, ?string $expectedValue = null): void
    {
        $type          = new SortableValueLabelListType();
        $builder       = $this->createMock(FormBuilderInterface::class);
        $eventListener = $this->getEventListenerFromBuildForm($type, $builder);
        $event         = $this->createMock(FormEvent::class);
        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);
        if ($shouldSetData) {
            $event->expects($this->once())
                ->method('setData')
                ->with($this->callback(function ($newData) use ($data, $expectedValue) {
                    return $newData['label'] === $data['label'] && $newData['value'] === $expectedValue;
                }));
        } else {
            $event->expects($this->never())
                ->method('setData');
        }
        $eventListener($event);
    }

    /**
     * @return array<string, array{mixed, bool, string|null}>
     */
    public static function eventListenerDataProvider(): array
    {
        return [
            'auto generates value' => [
                ['label' => 'Test Label', 'value' => ''],
                true,
                'test_label',
            ],
            'does not modify when value exists' => [
                ['label' => 'Test Label', 'value' => 'existing_value'],
                false,
                null,
            ],
            'does not modify when label empty' => [
                ['label' => '', 'value' => ''],
                false,
                null,
            ],
            'handles non-array data' => [
                'not_an_array',
                false,
                null,
            ],
        ];
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('slugifyDataProvider')]
    public function testFormEventListenerGeneratesSlug(string $input, string $expected): void
    {
        $type          = new SortableValueLabelListType();
        $builder       = $this->createMock(FormBuilderInterface::class);
        $eventListener = $this->getEventListenerFromBuildForm($type, $builder);
        $event         = $this->createMock(FormEvent::class);

        $data = ['label' => $input, 'value' => ''];
        $event->expects($this->once())
            ->method('getData')
            ->willReturn($data);

        if (!empty($input)) {
            $event->expects($this->once())
                ->method('setData')
                ->with($this->callback(function ($newData) use ($data, $expected) {
                    return $newData['label'] === $data['label'] && $newData['value'] === $expected;
                }));
        } else {
            $event->expects($this->never())
                ->method('setData');
        }

        $eventListener($event);
    }

    /**
     * @return array<int, array{string, string}>
     */
    public static function slugifyDataProvider(): array
    {
        return [
            ['My Option', 'my_option'],
            ['First Choice!', 'first_choice'],
            ['Test-Value_123', 'testvalue_123'],
            ['Special@#$%Characters', 'specialcharacters'],
            ['  Trimmed  Spaces  ', 'trimmed_spaces'],
            ['Multiple___Underscores', 'multiple_underscores'],
            ['Àccénted Chàracters', 'accented_characters'],
            ['Привет мир', 'privet_mir'],
            ['', ''],
            ['123Numbers', '123numbers'],
            ['Numéro', 'numero'],
            ['Âge', 'age'],
            ['Straße', 'strasse'],
            ['Über', 'uber'],
            ['Teléfono', 'telefono'],
            ['Dirección', 'direccion'],
            ['Coração', 'coracao'],
            ['Ação', 'acao'],
            ['Födelsedag', 'fodelsedag'],
            ['Äktenskap', 'aktenskap'],
            ['Номер', 'nomer'],
            ['Адрес', 'adres'],
            ['电话', 'dian_hua'],
            ['地址', 'de_zhi'],
            ['電話番号', 'dian_hua_fan_hao'],
            ['住所', 'zhu_suo'],
            ['رقم', 'rqm'],
            ['عنوان', 'nwan'],
            ['Adres', 'adres'],
            ['Yaş', 'yas'],
            ['Adresa', 'adresa'],
            ['Číslo', 'cislo'],
            ['Ulica', 'ulica'],
            ['Wiek', 'wiek'],
            ['Cím', 'cim'],
            ['Születésnap', 'szuletesnap'],
            ['Διεύθυνση', 'dieuthynse'],
            ['Ηλικία', 'elikia'],
            ['주소', 'juso'],
            ['전화번호', 'jeonhwabeonho'],
        ];
    }
}
