version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: "lockfile-only"
    groups:
      composer-prod-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
      composer-dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "phpstan/*"
      composer-phpstan-dependencies:
        patterns:
          - "phpstan/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: "lockfile-only"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
