version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    groups:
      all-dependencies:
        patterns:
          - "*"
