api:
  - "app/bundles/ApiBundle/**"
  
assets:
  - "app/bundles/AssetBundle/**"
  
campaigns:
  - "app/bundles/CampaignBundle/**"
  
categories:
  - "app/bundles/CategoryBundle/**"
  
channels:
  - "app/bundles/ChannelBundle/**"
  
companies:
  - "**/*company*"
  
configuration:
  - "app/bundles/ConfigBundle/**"
  
dashboard:
  - "app/bundles/DashboardBundle/**"
  
dynamic content:
  - "app/bundles/DynamicContentBundle/**"
  
email:
  - "app/bundles/EmailBundle/**"
  
forms:
  - "app/bundles/FormBundle/**"
  
import-export:
  - "**/*import*"
  
installation:
  - "app/bundles/InstallBundle/**"
  
integrations:
  - "app/bundles/IntegrationsBundle/**"
  
landing pages:
  - "app/bundles/PageBundle/**"
  
marketplace:
  - "app/bundles/MarketplaceBundle/**"
  
notifications:
  - "app/bundles/NotificationBundle/**"
  
plugin:
  - "app/bundles/PluginBundle/**"
  
points-scoring:
  - "app/bundles/PointBundle/**"
  
queue:
  - "app/bundles/QueueBundle/**"
  
reports:
  - "app/bundles/ReportBundle/**"
  
roles:
  - "app/bundles/UserBundle/**"
  
sms:
  - "app/bundles/SmsBundle/**"
  
stages:
  - "app/bundles/StageBundle/**"
  
translations:
  - "**/*.ini"
  
user-interface:
  - "**/*.less"
  - "**/*.css"
  
user-experience:
  - "**/*.twig"
  
webhooks:
  - "app/bundles/WebhookBundle/**"
  
widgets:
  - "**/*widget*"
