#!/usr/bin/env php
<?php

use Mautic\CoreBundle\Console\Output\ConsoleDatetimeOutput;
use Symfony\Component\Console\Input\ArgvInput;

require_once __DIR__.'/../autoload.php';

$input  = new ArgvInput();
$output = (false !== $input->getParameterOption(['--no-interaction', '-n'])) ? new ConsoleDatetimeOutput() : null;

$application = include dirname(__DIR__).'/app/console-application.php';
$application->run($input, $output);
