<?php

/**
 * @file
 * Includes the autoloader created by Composer.
 *
 * This file was generated by mautic-scaffold.
 *.
 * @see composer.json
 * @see index.php
 */

return require __DIR__ . '/vendor/autoload.php';
