#!/usr/bin/env php
<?php

if (function_exists('set_time_limit')) {
    set_time_limit(0);
}

require_once __DIR__.'/app/autoload.php';
require_once(__DIR__ . '/app/config/local.php');

if (!$parameters || !isset($parameters['mailer_from_name'])) return;

use Symfony\Component\Console\Input\ArgvInput;
$input = new ArgvInput();

echo shell_exec('php ' . __DIR__ . '/app/console ' . $input);
