<?php

declare(strict_types=1);

namespace Mautic\CoreBundle\Tests\Unit\Doctrine\Query;

use Mautic\CoreBundle\Doctrine\Query\QueryBuilder;
use Mautic\CoreBundle\Test\Doctrine\MockedConnectionTrait;
use PHPUnit\Framework\Attributes\AllowMockObjectsWithoutExpectations;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

#[AllowMockObjectsWithoutExpectations]
final class QueryBuilderTest extends TestCase
{
    use MockedConnectionTrait;

    /**
     * @return iterable<string, array{string}>
     */
    public static function provideWriteStatements(): iterable
    {
        yield 'delete' => ['delete'];
        yield 'update' => ['update'];
        yield 'insert' => ['insert'];
    }

    /**
     * DBAL switches back to a SELECT when select() is called, so a reused builder must
     * not keep generating the write statement it was previously given.
     */
    #[DataProvider('provideWriteStatements')]
    public function testSelectAfterWriteStatementGeneratesSelect(string $writeMethod): void
    {
        $queryBuilder = new QueryBuilder($this->getMockedConnection());
        $queryBuilder->{$writeMethod}('leads');

        $queryBuilder->select('id')->from('leads', 'l');

        $this->assertSame('SELECT id FROM leads l', $queryBuilder->getSQL());
    }

    #[DataProvider('provideWriteStatements')]
    public function testAddSelectAfterWriteStatementGeneratesSelect(string $writeMethod): void
    {
        $queryBuilder = new QueryBuilder($this->getMockedConnection());
        $queryBuilder->{$writeMethod}('leads');

        $queryBuilder->addSelect('id')->from('leads', 'l');

        $this->assertSame('SELECT id FROM leads l', $queryBuilder->getSQL());
    }

    /**
     * The write statements themselves must still be generated by DBAL.
     */
    public function testWriteStatementStillGeneratesWriteSql(): void
    {
        $queryBuilder = new QueryBuilder($this->getMockedConnection());
        $queryBuilder->delete('leads')->where('id = 1');

        $this->assertSame('DELETE FROM leads WHERE id = 1', $queryBuilder->getSQL());
    }
}
