<?php
/**
 * @package     Mautic
 * @copyright   2014 Mautic, NP. All rights reserved.
 * @author      Mautic
 * @link        http://mautic.com
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace Mautic\ApiBundle\Entity;

use Doctrine\ORM\QueryBuilder;
use Mautic\CoreBundle\Entity\CommonRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\NoResultException;
use Mautic\UserBundle\Entity\User;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends CommonRepository
{

    public function getUserClients(User $user)
    {
        $result = $this->createQueryBuilder('c')
            ->join('c.users', 'u')
            ->where("u.id = " . $user->getId())
            ->getQuery()
            ->getResult();
        return $result;
    }

    /**
     * {@inheritdoc}
     *
     * @param array $args
     * @return Paginator
     */
    public function getEntities($args = array())
    {
        $q = $this
            ->createQueryBuilder('c');

        if (!$this->buildClauses($q, $args)) {
            return array();
        }
        $query = $q->getQuery();
        $result = new Paginator($query);
        return $result;
    }

    protected function addCatchAllWhereClause(QueryBuilder &$q, $filter)
    {
        $unique  = $this->generateRandomParameterName(); //ensure that the string has a unique parameter identifier
        $string  = ($filter->strict) ? $filter->string : "%{$filter->string}%";

        $expr = $q->expr()->orX(
            $q->expr()->like('c.name',  ':'.$unique),
            $q->expr()->like('c.redirectUris', ':'.$unique)
        );

        if ($filter->not) {
            $expr = $q->expr()->not($expr);
        }

        return array(
            $expr,
            array("$unique" => $string)
        );
    }

    protected function addSearchCommandWhereClause(QueryBuilder &$q, $filter)
    {
        $command         = $field = $filter->command;
        $unique          = $this->generateRandomParameterName();
        $returnParameter = true; //returning a parameter that is not used will lead to a Doctrine error
        $expr            = false;

        switch ($command) {
            case $this->translator->trans('mautic.core.searchcommand.name'):
                $expr = $q->expr()->like("c.name", ':'.$unique);
                break;
            case $this->translator->trans('mautic.api.client.searchcommand.redirecturi'):
                $expr = $q->expr()->like('c.redirectUris', ":$unique");
                break;
        }


        $string  = ($filter->strict) ? $filter->string : "%{$filter->string}%";
        if ($expr && $filter->not) {
            $expr = $q->expr()->not($expr);
        }
        return array(
            $expr,
            ($returnParameter) ? array("$unique" => $string) : array()
        );

    }

    public function getSearchCommands()
    {
        return array(
            'mautic.core.searchcommand.name',
            'mautic.api.client.searchcommand.redirecturi',
        );
    }

    protected function getDefaultOrderBy()
    {
        return 'c.name';
    }

}
