<?php

namespace Mautic\CoreBundle\Form\Type;

use Mautic\CoreBundle\Helper\InputHelper;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

/**
 * @extends AbstractType<mixed>
 */
class SortableValueLabelListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label'          => 'mautic.core.label',
                'error_bubbling' => true,
                'attr'           => ['class' => 'form-control'],
            ]
        );

        $builder->add(
            'value',
            TextType::class,
            [
                'label'          => 'mautic.core.value_autogenerated',
                'error_bubbling' => true,
                'required'       => false,
                'attr'           => ['class' => 'form-control'],
            ]
        );

        $builder->addEventListener(
            FormEvents::PRE_SUBMIT,
            function (FormEvent $event): void {
                $data = $event->getData();

                if (is_array($data)
                    && (!isset($data['value']) || '' === $data['value'])
                    && !empty($data['label'])
                ) {
                    $data['value'] = $this->generateSlugFromLabel((string) $data['label']);
                    $event->setData($data);
                }
            }
        );
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        parent::buildView($view, $form, $options);

        $view->vars['preaddonAttr']  = $options['attr']['preaddon_attr'] ?? [];
        $view->vars['postaddonAttr'] = $options['attr']['postaddon_attr'] ?? [];
        $view->vars['preaddon']      = $options['attr']['preaddon'] ?? [];
        $view->vars['postaddon']     = $options['attr']['postaddon'] ?? [];
    }

    private function generateSlugFromLabel(string $label): string
    {
        $transliterated = InputHelper::transliterate($label);
        if (false === $transliterated) {
            return '';
        }
        $alphanumeric = InputHelper::alphanum($transliterated, false, '_');
        $trimmed      = trim($alphanumeric, '_');
        $normalized   = preg_replace('/_+/', '_', $trimmed);

        return strtolower($normalized ?? '');
    }
}
