<?php
/**
 * @package     Mautic
 * @copyright   2014 Mautic, NP. All rights reserved.
 * @author      Mautic
 * @link        http://mautic.com
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace Mautic\UserBundle\Entity;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\NoResultException;
use Mautic\CoreBundle\Entity\CommonRepository;
use Symfony\Bundle\FrameworkBundle\Translation\Translator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends CommonRepository
{

    /**
     * Checks to ensure that a username and/or email is unique
     *
     * @param $params
     * @return array
     */
    public function checkUniqueUsernameEmail($params) {
        $identifier = (isset($params['email'])) ? $params['email'] : $params['username'];
        $q = $this
            ->createQueryBuilder('u')
            ->where('u.username = :identifier OR u.email = :identifier')
            ->setParameter("identifier", $identifier)
            ->getQuery();
        return $q->getResult();
    }

    /**
     * Get a list of users
     *
     * @param array      $args
     * @param Translator $translator
     * @return Paginator
     */
    public function getEntities($args = array())
    {
        $q = $this
            ->createQueryBuilder('u')
            ->select('u, r')
            ->leftJoin('u.role', 'r');

        if (!$this->buildClauses($q, $args)) {
            return array();
        }

        $query = $q->getQuery();
        $result = new Paginator($query);
        return $result;
    }

    /**
     * Get a list of users for an autocomplete input
     *
     * @param string $search
     * @param int    $limit
     * @param int    $start
     * @return array
     */
    public function getUserList($search = '', $limit = 10, $start = 0)
    {
        $q = $this->_em->createQueryBuilder();

        $q->select('partial u.{id, firstName, lastName}')
            ->from('MauticUserBundle:User', 'u');
        if (!empty($search)) {
            $q->where(
                $q->expr()->orX(
                    $q->expr()->like('u.firstName', ':search'),
                    $q->expr()->like('u.lastName', ':search'),
                    $q->expr()->like(
                        $q->expr()->concat('u.firstName',
                            $q->expr()->concat(
                                $q->expr()->literal(' '),
                                'u.lastName'
                            )
                        ),
                        ':search'
                    )
                )
            )
            ->setParameter('search', "{$search}%");
        }

        $q->orderBy('u.firstName, u.lastName');

        if (!empty($limit)) {
            $q->setFirstResult($start)
                ->setMaxResults($limit);
        }

        $results = $q->getQuery()->getArrayResult();
        return $results;
    }

    /**
     * @param string $search
     * @param int    $limit
     * @param int    $start
     */
    public function getPositionList($search = '', $limit = 10, $start = 0)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('u.position')
            ->distinct()
            ->from('MauticUserBundle:User', 'u')
            ->where("u.position != ''")
            ->andWhere("u.position IS NOT NULL");
        if (!empty($search)) {
            $q->andWhere('u.position LIKE :search')
                ->setParameter('search', "{$search}%");
        }

        $q->orderBy('u.position');

        if (!empty($limit)) {
            $q->setFirstResult($start)
                ->setMaxResults($limit);
        }

        $results = $q->getQuery()->getArrayResult();
        return $results;
    }

    /**
     * @param QueryBuilder $q
     * @param              $filter
     * @return array
     */
    protected function addCatchAllWhereClause(QueryBuilder &$q, $filter)
    {
        $unique  = $this->generateRandomParameterName(); //ensure that the string has a unique parameter identifier
        $string  = ($filter->strict) ? $filter->string : "%{$filter->string}%";
        $func    = ($filter->not) ? "notLike" : "like";
        $xFunc   = ($func == "notLike") ? "andX" : "orX";

        $expr = $q->expr()->$xFunc(
            $q->expr()->$func('u.username',  ':'.$unique),
            $q->expr()->$func('u.email',     ':'.$unique),
            $q->expr()->$func('u.firstName', ':'.$unique),
            $q->expr()->$func('u.lastName',  ':'.$unique),
            $q->expr()->$func('u.position',  ':'.$unique),
            $q->expr()->$func('r.name',  ':'.$unique)
        );
        return array(
            $expr,
            array("$unique" => $string)
        );
    }

    /**
     * @param QueryBuilder $q
     * @param              $filter
     * @return array
     */
    protected function addSearchCommandWhereClause(QueryBuilder &$q, $filter)
    {
        $command         = $field = $filter->command;
        $string          = $filter->string;
        $unique          = $this->generateRandomParameterName();
        $returnParameter = true; //returning a parameter that is not used will lead to a Doctrine error
        $func            = ($filter->not) ? "notLike" : "like";
        $expr            = false;
        switch ($command) {
            case $this->translator->trans('mautic.core.searchcommand.is'):
                $isFunc = ($filter->not) ? "neq" : "eq";
                switch($string) {
                    case $this->translator->trans('mautic.user.user.searchcommand.isactive'):
                        $expr = $q->expr()->$isFunc("u.isActive", 1);
                        break;
                    case $this->translator->trans('mautic.user.user.searchcommand.isinactive'):
                        $expr = $q->expr()->$isFunc("u.isActive", 0);
                        break;
                    case $this->translator->trans('mautic.user.user.searchcommand.isadmin');
                        $expr = $q->expr()->$isFunc("r.isAdmin", 1);
                        break;
                }
                $returnParameter = false;
                break;
            case $this->translator->trans('mautic.user.user.searchcommand.email'):
                $expr = $q->expr()->$func("u.email", ':'.$unique);
                break;
            case $this->translator->trans('mautic.user.user.searchcommand.position'):
                $expr = $q->expr()->$func("u.position", ':'.$unique);
                break;
            case $this->translator->trans('mautic.user.user.searchcommand.username'):
                $expr = $q->expr()->$func("u.username", ':'.$unique);
                break;
            case $this->translator->trans('mautic.user.user.searchcommand.role'):
                $expr = $q->expr()->$func("r.name", ':'.$unique);
                break;
            case $this->translator->trans('mautic.core.searchcommand.name'):
                $xFunc = ($filter->not) ? "andX" : "orX";
                $expr = $q->expr()->$xFunc(
                    $q->expr()->$func('u.firstName', ':'.$unique),
                    $q->expr()->$func('u.lastName', ':'.$unique)
                );
                break;
        }

        $string  = ($filter->strict) ? $filter->string : "%{$filter->string}%";
        return array(
            $expr,
            ($returnParameter) ? array("$unique" => $string) : array()
        );

    }

    /**
     * @return array
     */
    public function getSearchCommands()
    {
         return array(
            'mautic.user.user.searchcommand.email',
            'mautic.core.searchcommand.is' => array(
                'mautic.user.user.searchcommand.isactive',
                'mautic.user.user.searchcommand.isinactive',
                'mautic.user.user.searchcommand.isadmin'
            ),
            'mautic.core.searchcommand.name',
            'mautic.user.user.searchcommand.position',
            'mautic.user.user.searchcommand.role',
            'mautic.user.user.searchcommand.username'
        );

    }

    /**
     * @return string
     */
    protected function getDefaultOrderBy()
    {
        return 'u.lastName, u.firstName, u.username';
    }
}