<?php
/**
 * @package     Mautic
 * @copyright   2014 Mautic, NP. All rights reserved.
 * @author      Mautic
 * @link        http://mautic.com
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace Mautic\LeadBundle\Entity;

use Mautic\CoreBundle\Entity\CommonRepository;

/**
 * SocialMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialMediaRepository extends CommonRepository
{

    public function getEntity($service = '')
    {
        $result = $this->createQueryBuilder('s')
            ->where('s.service = :service')
            ->setParameter('service', $service)
            ->getQuery()
            ->getArrayResult();

        return (!empty($result)) ? $result[0] : $result;
    }
}
