<?php
 //[STAMP] 6476198ea592cc0d7ef8cc10d992299b

namespace Mautic\CoreBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
