<?php
 //[STAMP] a4705bfb025d9523b00a0d293ba1e2f3

namespace Mautic\CoreBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
