<?php

declare(strict_types=1);
/**
 * @copyright   2020 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @see        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace MauticPlugin\MauticTrelloBundle\Service;

use Exception;
use InvalidArgumentException;
use GuzzleHttp\Client as HttpClient;
use Mautic\CoreBundle\Helper\CoreParametersHelper;
use Mautic\PluginBundle\Helper\IntegrationHelper;
use MauticPlugin\MauticTrelloBundle\Integration\TrelloIntegration;
use MauticPlugin\MauticTrelloBundle\Openapi\lib\Api\DefaultApi;
use MauticPlugin\MauticTrelloBundle\Openapi\lib\ApiException;
use MauticPlugin\MauticTrelloBundle\Openapi\lib\Configuration;
use MauticPlugin\MauticTrelloBundle\Openapi\lib\Model\Card;
use Monolog\Logger;

/**
 * Provide the auto generated Trello API to the MauticTrelloBundle.
 */
class TrelloApiService
{
    /**
     * @var bool|TrelloIntegration
     */
    protected $integration;

    /**
     * @var CoreParametersHelper
     */
    protected $coreParametersHelper;

    /**
     * @var Logger
     */
    protected $logger;

    /**
     * Set up the Trello Service.
     */
    public function __construct(IntegrationHelper $integrationHelper, CoreParametersHelper $coreParametersHelper, Logger $logger)
    {
        $this->integration          = $integrationHelper->getIntegrationObject('Trello');
        $this->coreParametersHelper = $coreParametersHelper;
        $this->logger               = $logger;
    }

    /**
     * Return the Api to Trello. Autogenerated, based on OpenAPI.
     *
     * @return DefaultApi|bool
     */
    public function getApi()
    {
        // setup auth
        $auth = $this->getAuthParams();
        if (!$this->integration->isPublished() || empty($auth['key'])) {
            return false;
        }
        $config = Configuration::getDefaultConfiguration()->setApiKey('key', $auth['key']);
        $config = Configuration::getDefaultConfiguration()->setApiKey('token', $auth['token']);

        return new DefaultApi(
            new HttpClient(),
            $config
        );
    }

    /**
     * Get all Trello boards as an array (id => name).
     *
     * @param string $filter
     */
    public function getBoardsArray($filter = 'open'): array
    {
        try {
            $api = $this->getApi();
            if (!$api) {
                return [];
            }

            $fields      = 'id,name';
            $boards      = $api->getBoards($fields, $filter);
            $boardsArray = [];
            foreach ($boards as $board) {
                $boardsArray[$board->getId()] = $board->getName();
            }

            return $boardsArray;
        } catch (ApiException $e) {
            $this->logger->warning('API Exception when calling DefaultApi->getBoards(): ', [$e->getMessage()]);

            return [];
        }
    }

    /**
     * Get the users favourite board from Settings.
     *
     * @return string
     */
    public function getFavouriteBoard()
    {
        return $this->coreParametersHelper->get('favorite_board', '');
    }

    /**
     * Get all the lists on the Trello board.
     *
     * @param int $boardId Trello Board id
     */
    public function getListsOnBoard(int $boardId = null): array
    {
        $api = $this->getApi();
        if (!$api) {
            return [];
        }

        if (empty($boardId)) {
            $boardId = $this->getFavouriteBoard();
            if (empty($boardId)) {
                $this->logger->warning('no board configured');

                return [];
            }
        }

        try {
            return $api->getLists($boardId);
        } catch (ApiException $e) {
            $this->logger->warning('API Exception when calling DefaultApi->getLists(): ', [$e->getMessage()]);

            return [];
        } catch (Exception $e) {
            $this->logger->warning('Exception when calling DefaultApi->getLists(): ', [$e->getMessage()]);

            return [];
        }
    }

    /**
     * Get the user specific auth params of the Trello API to add to the post part.
     *
     * @return array
     */
    public function getAuthParams(): array
    {
        if (!$this->integration || !$this->integration->isPublished()) {
            return [];
        }
        $keys = $this->integration->getIntegrationSettings()->getApiKeys();

        if (empty($keys['appkey']) || empty($keys['apitoken'])) {
            $this->logger->warning('No valid Trello api keys');
        }

        $encryptedKeys = [
            'key'   => isset($keys['appkey']) ? $keys['appkey'] : '',
            'token' => isset($keys['apitoken']) ? $keys['apitoken'] : '',
        ];

        $keys = $this->integration->decryptApiKeys($encryptedKeys);

        return $keys;
    }

    /**
     * * All the business logic for a submitted form.
     *
     * @return Card | Exception
     */
    public function addNewCard(array $card)
    {
        $api = $this->getApi();
        if (!$api) {
            return new Card();
        }

        try {
            $card = $api->addCard($card);
            $this->logger->debug('Successfully added card to Trello', [$card->getIdList(), $card->getId(), $card->getName()]);

            return $card;
        } catch (InvalidArgumentException $e) {
            $this->logger->warning($e->getMessage(), $e->getTrace());
            $error = new Error();
            $error->setCode('InvalidArgument');
            $error->setMessage($e->getMessage());

            return new Exception($error);
        } catch (Exception $e) {
            $this->logger->error($e->getMessage(), $e->getTrace());

            return new Exception($e->getMessage());
        }

        // return $this->redirectToRoute('task_success');
    }
}
