<?php
/**
 * @package     Mautic
 * @copyright   2014 Mautic, NP. All rights reserved.
 * @author      Mautic
 * @link        http://mautic.com
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace Mautic\LeadBundle\Entity;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Mautic\CoreBundle\Entity\CommonRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * LeadFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadFieldRepository extends CommonRepository
{

    /**
     * Retrieves array of aliases used to ensure unique alias for new fields
     *
     * @param $exludingId
     * @return array
     */
    public function getAliases($exludingId)
    {
        $q = $this->createQueryBuilder('l')
            ->select('l.alias')
            ->where('l.id != :id')
            ->setParameter('id', $exludingId);

        $results = $q->getQuery()->getArrayResult();
        return $results;
    }
}
