name: Issue bounties
on:
  issues:
    types: [opened, labeled]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js environment
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd .github/scripts/
          npm ci
    
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: node .github/scripts/bounties.js
